[package]
name = "private_voting"
type = "contract"
authors = ["Aztec Identity Hackathon"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.5", directory = "noir-projects/aztec-nr/aztec" }
